version: '2'
services:
  postgres:
    image: postgres:11.5
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: "job-service"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
